### PR TITLE
Use incrementing number instead of UUID for duplicate documents

### PR DESCRIPTION
**Pull request by alexanderbarnhill**
Make the addition of duplicate documents more practical

### CODE REVIEW

**Comment by markuswich** [comment]
your version numbers break the solr queries, because "(" and ")" are special characters. I tried to fix it like this:
```python
def _get(self, doc: str) -> SolrDoc:
        special_chars = re.compile(r'(?<!\\)(?P<char>[&|+\-!(){}[\]^"~*?:])')
        doc_formated = special_chars.sub(r'\\\g<char>', doc)
        # TODO don't know 100% whether this can fail or not
        query = f"id:*{doc_formated}"
        res = self.con.search(query)
        hit = self._get_hit(res, doc)
        if hit is None:
            return None
        return SolrDoc.from_hit(hit)
```
but I'm not sure if it works 100%

**Comment by alexanderbarnhill** [comment]
> your version numbers break the solr queries, because "(" and ")" are special characters. I tried to fix it like this:
> 
> ```python
> def _get(self, doc: str) -> SolrDoc:
>         special_chars = re.compile(r'(?<!\\)(?P<char>[&|+\-!(){}[\]^"~*?:])')
>         doc_formated = special_chars.sub(r'\\\g<char>', doc)
>         # TODO don't know 100% whether this can fail or not
>         query = f"id:*{doc_formated}"
>         res = self.con.search(query)
>         hit = self._get_hit(res, doc)
>         if hit is None:
>             return None
>         return SolrDoc.from_hit(hit)
> ```
> 
> but I'm not sure if it works 100%

I could also just remove the parentheses? Its not like they're necessary. just `_1`, `_2`, etc.

**Comment by markuswich** [comment]
it doesn't matter to me, but then the problem still exists, when uploading files containing special characters in their name

**Comment by alexanderbarnhill** [comment]
True. Then your solution is good enough for me.

**Comment by Alma-hanif** [comment]
- looks good to me

**Pull request merged**
