### PR TITLE
Hierarchical clustering using ward method and precomputed distance from tf-idf-vectorizer

### PR DESCRIPTION
**Pull request by Alma-hanif**

### CODE REVIEW

**Comment by alexanderbarnhill** [comment]
image

Results from a group of 49 PDFs

**Comment by Alma-hanif** [comment]
@alexanderbarnhill  can you please check results only on .txt files for now as I have done file reading with the text files in this commit.

**Comment by Alma-hanif** [comment]
> image
> 
> Results from a group of 49 PDFs

@alexanderbarnhill can you please check results only on .txt files for now as I have done file reading with the text files in this commit.

**Comment by alexanderbarnhill** [comment]
Yeah that works fine. Looks good. Just wasn't sure if you had tried other document types.

**Pull request merged**
