### PR TITLE
Tags

### PR DESCRIPTION
**Pull request by n-sakib**
- View tags
- Add tags
- Remove tags
- Test tag addition/removal

### CODE REVIEW

**Comment by markuswich** [comment]
looks good, but should it not send the tags to the backend db?

**Comment by n-sakib** [comment]
@alexanderbarnhill Added public/private in methods. Also tried to remove warning but there is still one left with 'document-view-table'. Maybe @markuswich can take a look at it. 

@markuswich You are right. I have added the backend logics but as for now, its just dummy data from the server side. I followed the task definition where it says I don't need to connect to db, just need to use dummy data.

**Comment by alexanderbarnhill** [comment]
@n-sakib Please remove all `.pyc` files and add a line to the `.gitignore` to exclude them automatically in the future.

**Comment by markuswich** [comment]
I fixed the warnings.

**Comment by markuswich** [comment]
btw the code that sends the post request is commented out so nothing gets actually send to the backend, is that intended?

**Comment by n-sakib** [comment]
Yeah, it doesn’t do anything yet.

**Pull request merged**
