### PR TITLE
added frontend interface for dimension/keyword input

### PR DESCRIPTION
**Pull request by markuswich**
I have added a layout for the keyword model page and added the input elements for the new keywords/dimensions.

### CODE REVIEW

**Comment by markuswich** [comment]
There are 2 problems I'm facing:

1. Keeping the later drag&drop functionality in mind I used cdkDropList for now, but I'm not 100% sure if it fulfills all our needs because dragging into a treeview seems like a pain. If you guys have any better ideas let me know.

2. I can't figure out how I need to change the css so that the lists are fixed to the top of the mat-grid-tile and grow downwards. Once the bottom is reached they should become scrollable. Any fixes?

**Comment by alexanderbarnhill** [comment]
> There are 2 problems I'm facing:
> 
> 1. Keeping the later drag&drop functionality in mind I used cdkDropList for now, but I'm not 100% sure if it fulfills all our needs because dragging into a treeview seems like a pain. If you guys have any better ideas let me know.
> 2. I can't figure out how I need to change the css so that the lists are fixed to the top of the mat-grid-tile and grow downwards. Once the bottom is reached they should become scrollable. Any fixes?

I just pushed what could be a fix to point 2. Have a look and let me know what you think. As for point 1, we may need to rethink how we do that. Drag and Drop has always been a pain for me. Maybe we could do a modal box instead where we actively select what we want to add to our hierarchy? I'm not sure.

**Comment by markuswich** [comment]
The scrolling is exactly what I had in mind, but the tile goes out of my screen now. Might be because of small resolution. How does it look for you?
Frontend - Mozilla Firefox_004

**Comment by alexanderbarnhill** [comment]
> The scrolling is exactly what I had in mind, but the tile goes out of my screen now. Might be because of small resolution. How does it look for you?
> Frontend - Mozilla Firefox_004

yeah have a look at it now.

**Comment by markuswich** [comment]
works for me, thx for the help

**Pull request merged**
