### PR TITLE
added pagination to the backend

### PR DESCRIPTION
**Pull request by Dimfred**
- FRONTEND MISSING RIGHTNOW (will be added by @n-sakib)

- pagination with sorting parameters added to the backend
- modified the `documents` endpoint to receive parameters
- the `creation_date` is now updated on every change on a document
- modified `schema.xml` in order for Solr to receive `str` querries on `creation_date` and `size`

### CODE REVIEW

**Comment by markuswich** [comment]
Dont you need to add the search term to the query as well? Because in the front end you can only search the documents you currently have, which would be just one page.

**Comment by Dimfred** [comment]
> Dont you need to add the search term to the query as well? Because in the front end you can only search the documents you currently have, which would be just one page.

By search term you probably mean a `keyword` correct? Yes you are right entrirely forgot that thx.

**Comment by markuswich** [comment]
I mean the string you input into the search bar in the front end. Right now we use it to search every field that is visible in the doc table except the date.

**Comment by Dimfred** [comment]
Ah yeah got it. The search should be performed on the backend side. But we should then include an active trigger to the frontend, I suppose.

**Comment by markuswich** [comment]
Maybe, but maybe updates after every key press is fast enough, either way it is only front end changes and shouldnt matter for the back end code.

**Comment by Dimfred** [comment]
When you do the search term only in the frontend the whole use of the app is useless. You have to do in the backend.

**Comment by markuswich** [comment]
im not saying you should only do it in the frontend, im saying everytime you change the search term you send a request to the backend and for the backend it doesnt matter if you send that the request after every keystroke or after pressing a search button. Is it really that slow? Sending the data of 20 files or whatever shouldnt take that long and if the backend and solr run on the same hardware solr queries shouldnt take that long.

**Comment by Dimfred** [comment]
I think it will be slow, but this would be the nicest behavior, I agree. We do it like you say and see how it works.

**Pull request merged**
